### PR TITLE
opening the style pr again

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by tgamblin** [comment]
Why open again? Was the prior one getting too long?

**Comment by vsoch** [comment]
No there was a gray message on both my PRs that the branch could not be integrated with main. I tried several things and no avail. The only way to not lose the work was to re-create it.

**Comment by vsoch** [comment]
A1C47861-10C5-491D-AD5A-F1409AB28D42

**Comment by vsoch** [comment]
It didn’t work doing locally either, I pushed commits after a rebase and the message was still there. Frustrating.

**Comment by tgamblin** [comment]
I fixed the other one so closing this one -- I guess I had not enabled squash merges -- they're on now so hopefully that saves you work in the future.

**Pull request closed without merging**
